version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: complaint-postgres
    restart: always
    # .env 파일에 정의된 변수를 사용하거나 직접 입력하세요
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      POSTGRES_DB: ${POSTGRES_DB:-complaint_db}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - complaint-network
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_HOST=0.0.0.0
      #- LANGFLOW_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/complaint_db
    depends_on:
      - db
    networks:
    - complaint-network

networks:
  complaint-network:
    driver: bridge